### ISSUE TITLE
Layout request: CarpalX

### ISSUE THREAD

**Issue by zamadatix** [davidebeatrici/kli#1]
Is there any example of the .ini file structure needed by the program? I was able to follow the errors until product_code where I'm having trouble figuring out exactly what it wants put there. I'm sure there are more fields after as well.

Thanks!

**Comment by davidebeatrici** [comment]
Thanks for your interest!

I made a pull request a while ago that you can use as example: thomasfaingnaert/win-us-intl-altgr#6

**Comment by zamadatix** [comment]
Thanks for the quick response! I was able to make a .ini based on that example but I seem to be hitting some sort of problem:

![image](https://user-images.githubusercontent.com/343550/145495970-3ed97a4f-b14f-47bf-9f0c-b3ea5eb79558.png)

The .klc validates in MSKLC so I don't think it's a bad layout file causing the problem but it's uploaded here [carpalx.txt](https://github.com/davidebeatrici/kli/files/7689243/carpalx.txt) if you want to see it (as .txt instead of .klc for GitHub). The .ini I came up with is:

```
[install]
language_id = 0x0409
product_code = {0b4424de-a840-4dac-b91a-01bfdbf99419}

[layout]
file = carpalx.klc
text = carpalx

display_name = carpalx
```

The goal being adding the carpalx layout to EN-US on an ARM64 version of Windows (and the ARM64 binary was used of course).

Appreciate any insight you may have into why it's throwing this error, thanks again for your help up until this point.

**Comment by davidebeatrici** [comment]
The `.klc` extension indicates that it's an MSKLC project file. The layout has to be a shared library (`.dll`) in order to be loaded by Windows.

https://github.com/davidebeatrici/kli/wiki/Source-file(s)-from-MSKLC-project-file-(.klc)

Once you have the source code, you can build it using the CMake project in the pull request I linked.

**Comment by davidebeatrici** [comment]
CMake project: [CarpalX_CMake.zip](https://github.com/davidebeatrici/kli/files/7695626/CarpalX_CMake.zip)

I also built the layout for you: [CarpalX_Build.zip](https://github.com/davidebeatrici/kli/files/7695625/CarpalX_Build.zip)

The archive contains binaries for ARM64, x64 and x86.

**Comment by zamadatix** [comment]
Wow thank you!

**Comment by davidebeatrici** [comment]
No problem, feel free to create a repository for it!
