### ISSUE TITLE
Layout request: ItaLinux

### ISSUE THREAD

**Issue by h1v9** [davidebeatrici/kli#3]
The project is really interesting, as it looks like the only way to compile a layout for arm64.
However, as C++ is not really my thing, it's not clear to me how to proceed?
Specifically I'm trying to compile this layout https://github.com/kolmogorov42/maiuscole-accentate

Could you please explain what I sould do? Thanks a lot

**Comment by davidebeatrici** [comment]
There is a wiki page that explains how to generate C source files using KbdTool: https://github.com/davidebeatrici/kli/wiki/Source-file(s)-from-MSKLC-project-file-(.klc)

Once you have those, it's just a matter of writing a CMake project and a KLI configuration file. Example: thomasfaingnaert/win-us-intl-altgr#6

Also see #1.

**Comment by davidebeatrici** [comment]
CMake project: [ItaLinux_CMake.zip](https://github.com/user-attachments/files/16227800/ItaLinux_CMake.zip)

I also built the layout for you: [ItaLinux_Build.zip](https://github.com/user-attachments/files/16227801/ItaLinux_Build.zip)

The archive contains binaries for ARM64, x64 and x86.

**Comment by h1v9** [comment]
I missed the wiki page.
Thanks a lot for providing it compiled, you saved me a lot of hassle

**Comment by davidebeatrici** [comment]
You're welcome!
